name: semana7_castillo
description: "A new Flutter project."
publish_to: "none"
version: 0.2.2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_database: ^12.0.2
  provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  firebase_auth: ^6.1.2
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  url_launcher: ^6.1.10
  http: ^1.2.0 # ðŸ‘ˆ AÃ±adido para evitar el error en ubicacion_screen.dart
  flutter_polyline_points: 3.1.0
  shimmer: ^3.0.0 # <--- Agrega esto
  image_picker: ^1.1.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5

flutter_native_splash:
  color: "#FFA500"
  image: assets/splash_logo.png
  android: true
  ios: true
  android_12:
    image: assets/splash_logo.png
    color: "#FFA500"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"
  android_adaptive_icon_background: "#FFA500"
  android_adaptive_icon_foreground: "assets/icono_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icono_app.png
